### PR TITLE
Fix depreciation warning

### PR DESCRIPTION
**Pull request by jniechcial**
There is opened issue but looks like it's dead already.

### CODE REVIEW

**Comment by jerel** [comment]
Thanks for the PR. Looks like we'll have to upgrade Ember CLI to get tests passing again. I'll try to get to it but it might be a few days yet. If you (or anyone) else wants to tackle it I'm happy to review and merge.

**Comment by jniechcial** [comment]
@jerel I upgraded ember-cli, ember and couple of other packages and fix the tests. I am not very content with your current acceptance test suite - you should take care of acceptance helpers (like `click`, etc.) but I am aware that they wrap the execution in `andThen`. Basically, it's useless as the addon wraps the run loop until the message disappear so the element won't be found.

For now, I think that this quick win is enough. Give me a sign what you think.

**Comment by jerel** [comment]
@jniechcial thanks a bunch for doing this upgrade!

**Comment by jniechcial** [comment]
No problem, thanks! Waiting for release ;)

**Comment by jerel** [comment]
Boom: https://www.npmjs.com/package/ember-cli-growl

**Comment by jniechcial** [comment]
Thanks, pleasure! :)

**Pull request merged**
